export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const SET_INGREDIENTS_SUCCESS = "SET_INGREDIENTS_SUCCESS";
export const SET_INGREDIENTS_FAILED = "SET_INGREDIENTS_FAILED";

export const INIT_PURCHASE_BURGER = "INIT_PURCHASE_BURGER";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";

export const INIT_FETCH_ORDERS = "INIT_FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_INITIATE = "AUTH_INITIATE";
export const AUTH_START = "AUTH_START";
export const AUTH_START_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH_START_FAIL = "AUTH_START_FAIL";
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS";

export const INITIATE_LOG_OUT = "INITIATE_LOG_OUT";
export const LOG_OUT = "LOG_OUT";
